


import type { Metadata } from "next";
import { Inter, Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { FavouriteProvider } from "@/app/wishlist/FavouriteContext"; // Import the FavouriteProvider

// Configure fonts with desired weights and subsets
const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });
const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "700"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* Wrap the entire layout with the FavouriteProvider */}
        <FavouriteProvider>
          <Header />
          {children}
          <Footer />
        </FavouriteProvider>
      </body>
    </html>
  );
}
